<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Achuthasai Valluru">

<title>Home Credit Default Risk: Exploratory Data Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="eda_files/libs/clipboard/clipboard.min.js"></script>
<script src="eda_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="eda_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="eda_files/libs/quarto-html/popper.min.js"></script>
<script src="eda_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="eda_files/libs/quarto-html/anchor.min.js"></script>
<link href="eda_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="eda_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="eda_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="eda_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="eda_files/libs/bootstrap/bootstrap-917079515d91bccb85b543faf8aa8bb6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#eda-questions" id="toc-eda-questions" class="nav-link" data-scroll-target="#eda-questions">EDA Questions</a></li>
  </ul></li>
  <li><a href="#description-of-the-data" id="toc-description-of-the-data" class="nav-link" data-scroll-target="#description-of-the-data">Description of the Data</a>
  <ul class="collapse">
  <li><a href="#dataset-dimensions" id="toc-dataset-dimensions" class="nav-link" data-scroll-target="#dataset-dimensions">Dataset Dimensions</a></li>
  <li><a href="#training-and-test-structure" id="toc-training-and-test-structure" class="nav-link" data-scroll-target="#training-and-test-structure">Training and Test Structure</a></li>
  <li><a href="#grain-and-primary-key" id="toc-grain-and-primary-key" class="nav-link" data-scroll-target="#grain-and-primary-key">Grain and Primary Key</a></li>
  <li><a href="#variable-groups" id="toc-variable-groups" class="nav-link" data-scroll-target="#variable-groups">Variable Groups</a></li>
  </ul></li>
  <li><a href="#data-integrity" id="toc-data-integrity" class="nav-link" data-scroll-target="#data-integrity">Data Integrity</a>
  <ul class="collapse">
  <li><a href="#which-variables-contain-substantial-missing-data" id="toc-which-variables-contain-substantial-missing-data" class="nav-link" data-scroll-target="#which-variables-contain-substantial-missing-data">Which Variables Contain Substantial Missing Data?</a></li>
  <li><a href="#are-there-unusual-numeric-values-that-could-affect-the-analysis" id="toc-are-there-unusual-numeric-values-that-could-affect-the-analysis" class="nav-link" data-scroll-target="#are-there-unusual-numeric-values-that-could-affect-the-analysis">Are There Unusual Numeric Values That Could Affect the Analysis?</a></li>
  <li><a href="#does-days_birth-contain-unrealistic-applicant-ages" id="toc-does-days_birth-contain-unrealistic-applicant-ages" class="nav-link" data-scroll-target="#does-days_birth-contain-unrealistic-applicant-ages">Does DAYS_BIRTH Contain Unrealistic Applicant Ages?</a></li>
  <li><a href="#are-there-unusual-values-in-the-categorical-variables" id="toc-are-there-unusual-values-in-the-categorical-variables" class="nav-link" data-scroll-target="#are-there-unusual-values-in-the-categorical-variables">Are There Unusual Values in the Categorical Variables?</a></li>
  </ul></li>
  <li><a href="#exploratory-results" id="toc-exploratory-results" class="nav-link" data-scroll-target="#exploratory-results">Exploratory Results</a>
  <ul class="collapse">
  <li><a href="#how-common-is-payment-difficulty-in-the-training-data" id="toc-how-common-is-payment-difficulty-in-the-training-data" class="nav-link" data-scroll-target="#how-common-is-payment-difficulty-in-the-training-data">How Common Is Payment Difficulty in the Training Data?</a></li>
  <li><a href="#applicant-demographics" id="toc-applicant-demographics" class="nav-link" data-scroll-target="#applicant-demographics">Applicant Demographics</a>
  <ul class="collapse">
  <li><a href="#how-does-applicant-age-differ-between-applicants-with-and-without-payment-difficulty" id="toc-how-does-applicant-age-differ-between-applicants-with-and-without-payment-difficulty" class="nav-link" data-scroll-target="#how-does-applicant-age-differ-between-applicants-with-and-without-payment-difficulty">How Does Applicant Age Differ Between Applicants With and Without Payment Difficulty?</a></li>
  <li><a href="#how-do-income-and-requested-credit-amounts-differ-between-applicants-with-and-without-payment-difficulty" id="toc-how-do-income-and-requested-credit-amounts-differ-between-applicants-with-and-without-payment-difficulty" class="nav-link" data-scroll-target="#how-do-income-and-requested-credit-amounts-differ-between-applicants-with-and-without-payment-difficulty">How Do Income and Requested Credit Amounts Differ Between Applicants With and Without Payment Difficulty?</a></li>
  </ul></li>
  <li><a href="#loan-characteristics" id="toc-loan-characteristics" class="nav-link" data-scroll-target="#loan-characteristics">Loan Characteristics</a>
  <ul class="collapse">
  <li><a href="#how-do-requested-credit-amounts-differ-between-applicants-with-and-without-payment-difficulty" id="toc-how-do-requested-credit-amounts-differ-between-applicants-with-and-without-payment-difficulty" class="nav-link" data-scroll-target="#how-do-requested-credit-amounts-differ-between-applicants-with-and-without-payment-difficulty">How Do Requested Credit Amounts Differ Between Applicants With and Without Payment Difficulty?</a></li>
  <li><a href="#what-relationships-exist-among-key-financial-variables-such-as-income-credit-amount-and-annuity-amount" id="toc-what-relationships-exist-among-key-financial-variables-such-as-income-credit-amount-and-annuity-amount" class="nav-link" data-scroll-target="#what-relationships-exist-among-key-financial-variables-such-as-income-credit-amount-and-annuity-amount">What Relationships Exist Among Key Financial Variables Such as Income, Credit Amount, and Annuity Amount?</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#ai-use" id="toc-ai-use" class="nav-link" data-scroll-target="#ai-use">AI Use</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Home Credit Default Risk: Exploratory Data Analysis</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Achuthasai Valluru </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Home Credit provides consumer financing to customers who may have limited or no traditional credit history. The business problem is to distinguish applicants who are more likely to experience payment difficulties from applicants who are capable of repayment. Better identification of credit risk could help Home Credit reduce losses associated with payment difficulties while avoiding unnecessary rejection of applicants who are likely to repay.</p>
<p>The purpose of this exploratory data analysis is to understand the application data, identify data-quality issues that may affect later modeling, and investigate applicant characteristics that may be associated with payment difficulty.</p>
<section id="eda-questions" class="level2">
<h2 class="anchored" data-anchor-id="eda-questions">EDA Questions</h2>
<p>The analysis will address the following questions:</p>
<ol type="1">
<li>How common is payment difficulty in the training data?</li>
<li>How does applicant age differ between applicants with and without payment difficulty?</li>
<li>How do income and requested credit amounts differ between applicants with and without payment difficulty?</li>
<li>What relationships exist among key financial variables such as income, credit amount, and annuity amount?</li>
<li>Which variables contain substantial missing data, unusual values, or other data-quality problems that must be addressed before modeling?</li>
<li>Are the training and test datasets structurally consistent enough to support the planned predictive analysis?</li>
</ol>
</section>
</section>
<section id="description-of-the-data" class="level1">
<h1>Description of the Data</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages used for data manipulation and visualization</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the required Home Credit application datasets</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>application_train <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Data/application_train.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>application_test <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Data/application_test.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="dataset-dimensions" class="level2">
<h2 class="anchored" data-anchor-id="dataset-dimensions">Dataset Dimensions</h2>
<p>The first step is to examine the size of the training and test datasets.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Report the number of rows and columns in each application dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Dataset =</span> <span class="fu">c</span>(<span class="st">"Training"</span>, <span class="st">"Test"</span>),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Rows =</span> <span class="fu">c</span>(<span class="fu">nrow</span>(application_train), <span class="fu">nrow</span>(application_test)),</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Columns =</span> <span class="fu">c</span>(<span class="fu">ncol</span>(application_train), <span class="fu">ncol</span>(application_test))</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Dataset   Rows Columns
1 Training 307511     122
2     Test  48744     121</code></pre>
</div>
</div>
<p>The training dataset contains 307,511 applications and 122 variables, while the test dataset contains 48,744 applications and 121 variables. The one-column difference is expected because the training data contain the <code>TARGET</code> variable indicating whether an applicant experienced payment difficulty, while the test data require this outcome to be predicted. Before modeling, the remaining variables should be checked to confirm that the training and test datasets have consistent structures.</p>
</section>
<section id="training-and-test-structure" class="level2">
<h2 class="anchored" data-anchor-id="training-and-test-structure">Training and Test Structure</h2>
<p>Because the training dataset contains one additional column, the column names are compared to determine whether <code>TARGET</code> is the only structural difference.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify columns that appear in only one of the two application datasets</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>train_only <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(<span class="fu">names</span>(application_train), <span class="fu">names</span>(application_test))</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>test_only <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(<span class="fu">names</span>(application_test), <span class="fu">names</span>(application_train))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Comparison =</span> <span class="fu">c</span>(<span class="st">"Training only"</span>, <span class="st">"Test only"</span>),</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Columns =</span> <span class="fu">c</span>(</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste</span>(train_only, <span class="at">collapse =</span> <span class="st">", "</span>),</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste</span>(test_only, <span class="at">collapse =</span> <span class="st">", "</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Comparison Columns
1 Training only  TARGET
2     Test only        </code></pre>
</div>
</div>
<p>The comparison confirms that TARGET is the only column present in the training data but absent from the test data. All predictor columns are shared between the two datasets. This is the expected structure for a supervised prediction problem: the training data provide known outcomes for model development, while the test data contain the same applicant information without the outcome. Therefore, no predictor columns need to be reconciled between the two datasets based on column names.</p>
</section>
<section id="grain-and-primary-key" class="level2">
<h2 class="anchored" data-anchor-id="grain-and-primary-key">Grain and Primary Key</h2>
<p>The application datasets are expected to contain one row per loan application. The uniqueness of <code>SK_ID_CURR</code> is checked to determine whether it can serve as the primary key.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check whether SK_ID_CURR uniquely identifies each row in the application datasets</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Dataset =</span> <span class="fu">c</span>(<span class="st">"Training"</span>, <span class="st">"Test"</span>),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Rows =</span> <span class="fu">c</span>(<span class="fu">nrow</span>(application_train), <span class="fu">nrow</span>(application_test)),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Unique_SK_ID_CURR =</span> <span class="fu">c</span>(</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">n_distinct</span>(application_train<span class="sc">$</span>SK_ID_CURR),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">n_distinct</span>(application_test<span class="sc">$</span>SK_ID_CURR)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Duplicate_SK_ID_CURR =</span> <span class="fu">c</span>(</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sum</span>(<span class="fu">duplicated</span>(application_train<span class="sc">$</span>SK_ID_CURR)),</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sum</span>(<span class="fu">duplicated</span>(application_test<span class="sc">$</span>SK_ID_CURR))</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Dataset   Rows Unique_SK_ID_CURR Duplicate_SK_ID_CURR
1 Training 307511            307511                    0
2     Test  48744             48744                    0</code></pre>
</div>
</div>
<p>The number of unique SK_ID_CURR values equals the number of rows in both datasets, and no duplicate identifiers were found. This confirms that SK_ID_CURR uniquely identifies each application record in both the training and test data. For this analysis, the application tables therefore have a grain of one row per current loan application, with SK_ID_CURR serving as the primary key. No duplicate application records need to be removed based on this identifier.</p>
</section>
<section id="variable-groups" class="level2">
<h2 class="anchored" data-anchor-id="variable-groups">Variable Groups</h2>
<p>The application datasets contain many variables describing different aspects of an applicant and the requested loan. The Home Credit data dictionary is used to better understand the meaning of these variables and organize the information available for exploratory analysis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the Home Credit data dictionary</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>column_description <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Data/HomeCredit_columns_description.csv"</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview the structure of the data dictionary</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(column_description)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 219
Columns: 5
$ ...1        &lt;dbl&gt; 1, 2, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1…
$ Table       &lt;chr&gt; "application_{train|test}.csv", "application_{train|test}.…
$ Row         &lt;chr&gt; "SK_ID_CURR", "TARGET", "NAME_CONTRACT_TYPE", "CODE_GENDER…
$ Description &lt;chr&gt; "ID of loan in our sample", "Target variable (1 - client w…
$ Special     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…</code></pre>
</div>
</div>
<p>Based on the data dictionary, the application data include several major groups of information that may be useful for understanding payment difficulty. These include applicant demographics and household characteristics, employment and income information, loan and annuity characteristics, housing and property information, external credit scores, contact and document indicators, regional information, and credit bureau inquiry information. The TARGET variable is the outcome in the training data and indicates whether an applicant experienced payment difficulties. These groups provide different perspectives on an applicant’s financial situation and may contain useful predictors of repayment risk.</p>
</section>
</section>
<section id="data-integrity" class="level1">
<h1>Data Integrity</h1>
<section id="which-variables-contain-substantial-missing-data" class="level3">
<h3 class="anchored" data-anchor-id="which-variables-contain-substantial-missing-data">Which Variables Contain Substantial Missing Data?</h3>
<p>Missing data can affect both exploratory analysis and later predictive modeling. The training data are examined to identify variables with substantial missingness and determine which variables may require special treatment during data preparation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number and percentage of missing values for each variable</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>missing_summary <span class="ot">&lt;-</span> application_train <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)))) <span class="sc">|&gt;</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"Variable"</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"Missing"</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Percent_Missing =</span> Missing <span class="sc">/</span> <span class="fu">nrow</span>(application_train) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Percent_Missing))</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the variables with the highest percentages of missing values</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>missing_summary <span class="sc">|&gt;</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">15</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 3
   Variable                 Missing Percent_Missing
   &lt;chr&gt;                      &lt;int&gt;           &lt;dbl&gt;
 1 COMMONAREA_AVG            214865            69.9
 2 COMMONAREA_MODE           214865            69.9
 3 COMMONAREA_MEDI           214865            69.9
 4 NONLIVINGAPARTMENTS_AVG   213514            69.4
 5 NONLIVINGAPARTMENTS_MODE  213514            69.4
 6 NONLIVINGAPARTMENTS_MEDI  213514            69.4
 7 FONDKAPREMONT_MODE        210295            68.4
 8 LIVINGAPARTMENTS_AVG      210199            68.4
 9 LIVINGAPARTMENTS_MODE     210199            68.4
10 LIVINGAPARTMENTS_MEDI     210199            68.4
11 FLOORSMIN_AVG             208642            67.8
12 FLOORSMIN_MODE            208642            67.8
13 FLOORSMIN_MEDI            208642            67.8
14 YEARS_BUILD_AVG           204488            66.5
15 YEARS_BUILD_MODE          204488            66.5</code></pre>
</div>
</div>
<p>The missing-value analysis shows substantial missingness in several variables, particularly those describing housing and property characteristics. COMMONAREA_AVG, COMMONAREA_MODE, and COMMONAREA_MEDI each have approximately 69.9% missing values, while several apartment, floor, and building-related variables are missing for more than 65% of applications. Because these variables are unavailable for a large portion of applicants, relying heavily on them could reduce the amount of usable information available for consistent default-risk prediction. During data preparation, variables with very high missingness should be evaluated individually to determine whether they provide enough useful information to retain or impute; otherwise, they may be excluded from modeling.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine whether missingness in a highly incomplete variable is associated with payment difficulty</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">COMMONAREA_AVG_Missing =</span> <span class="fu">if_else</span>(<span class="fu">is.na</span>(COMMONAREA_AVG), <span class="st">"Missing"</span>, <span class="st">"Not Missing"</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(COMMONAREA_AVG_Missing) <span class="sc">|&gt;</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Applicants =</span> <span class="fu">n</span>(),</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Payment_Difficulty_Rate =</span> <span class="fu">mean</span>(TARGET) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  COMMONAREA_AVG_Missing Applicants Payment_Difficulty_Rate
  &lt;chr&gt;                       &lt;int&gt;                   &lt;dbl&gt;
1 Missing                    214865                    8.57
2 Not Missing                 92646                    6.91</code></pre>
</div>
</div>
<p>Applicants with missing <code>COMMONAREA_AVG</code> values had a payment-difficulty rate of 8.57%, compared with 6.91% among applicants with non-missing values. This suggests that missingness in this variable is associated with payment difficulty and may contain useful predictive information rather than being purely random. Therefore, during data preparation, the missing values should not simply be ignored or the affected records automatically removed. The variable and its missingness should be evaluated as potential information for the predictive model.</p>
</section>
<section id="are-there-unusual-numeric-values-that-could-affect-the-analysis" class="level3">
<h3 class="anchored" data-anchor-id="are-there-unusual-numeric-values-that-could-affect-the-analysis">Are There Unusual Numeric Values That Could Affect the Analysis?</h3>
<p>Several variables represent applicant characteristics and time measurements. Selected variables are examined for unusual or potentially unrealistic values that could affect interpretation or later modeling.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine ranges for selected numeric variables</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Min_Days_Birth =</span> <span class="fu">min</span>(DAYS_BIRTH, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Max_Days_Birth =</span> <span class="fu">max</span>(DAYS_BIRTH, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Min_Days_Employed =</span> <span class="fu">min</span>(DAYS_EMPLOYED, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Max_Days_Employed =</span> <span class="fu">max</span>(DAYS_EMPLOYED, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Min_Income =</span> <span class="fu">min</span>(AMT_INCOME_TOTAL, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Max_Income =</span> <span class="fu">max</span>(AMT_INCOME_TOTAL, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Min_Credit =</span> <span class="fu">min</span>(AMT_CREDIT, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">Max_Credit =</span> <span class="fu">max</span>(AMT_CREDIT, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
  Min_Days_Birth Max_Days_Birth Min_Days_Employed Max_Days_Employed Min_Income
           &lt;dbl&gt;          &lt;dbl&gt;             &lt;dbl&gt;             &lt;dbl&gt;      &lt;dbl&gt;
1         -25229          -7489            -17912            365243      25650
# ℹ 3 more variables: Max_Income &lt;dbl&gt;, Min_Credit &lt;dbl&gt;, Max_Credit &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Investigate the unusual DAYS_EMPLOYED value</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Records_365243 =</span> <span class="fu">sum</span>(DAYS_EMPLOYED <span class="sc">==</span> <span class="dv">365243</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Percent_365243 =</span> <span class="fu">mean</span>(DAYS_EMPLOYED <span class="sc">==</span> <span class="dv">365243</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  Records_365243 Percent_365243
           &lt;int&gt;          &lt;dbl&gt;
1          55374           18.0</code></pre>
</div>
</div>
<p>The value 365243 appears in 55,374 records, representing approximately 18.0% of the training data. This is not a realistic number of employment days and appears to represent a special value rather than an actual employment duration. During data preparation, this value should therefore be treated separately rather than as a valid number of employment days so that it does not distort the relationship between employment history and payment difficulty.</p>
</section>
<section id="does-days_birth-contain-unrealistic-applicant-ages" class="level3">
<h3 class="anchored" data-anchor-id="does-days_birth-contain-unrealistic-applicant-ages">Does DAYS_BIRTH Contain Unrealistic Applicant Ages?</h3>
<p><code>DAYS_BIRTH</code> contains negative values because age is recorded as the number of days before the current loan application. Converting these values to approximate ages will make the range easier to interpret.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert DAYS_BIRTH to approximate age in years and examine the range</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Min_Age =</span> <span class="fu">min</span>(<span class="sc">-</span>DAYS_BIRTH <span class="sc">/</span> <span class="fl">365.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Max_Age =</span> <span class="fu">max</span>(<span class="sc">-</span>DAYS_BIRTH <span class="sc">/</span> <span class="fl">365.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Average_Age =</span> <span class="fu">mean</span>(<span class="sc">-</span>DAYS_BIRTH <span class="sc">/</span> <span class="fl">365.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  Min_Age Max_Age Average_Age
    &lt;dbl&gt;   &lt;dbl&gt;       &lt;dbl&gt;
1    20.5    69.1        43.9</code></pre>
</div>
</div>
<p>After converting DAYS_BIRTH from days to approximate years, applicant ages range from 20.5 to 69.1 years, with an average age of 43.9 years. These values appear reasonable for loan applicants. Therefore, the negative values in DAYS_BIRTH reflect how the variable is recorded rather than a data-quality problem.</p>
</section>
<section id="are-there-unusual-values-in-the-categorical-variables" class="level3">
<h3 class="anchored" data-anchor-id="are-there-unusual-values-in-the-categorical-variables">Are There Unusual Values in the Categorical Variables?</h3>
<p>Selected categorical variables are examined to identify unusual or unexpected category values that may require cleaning before modeling.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine values in selected categorical variables</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(CODE_GENDER)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  CODE_GENDER      n
  &lt;chr&gt;        &lt;int&gt;
1 F           202448
2 M           105059
3 XNA              4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(NAME_FAMILY_STATUS)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  NAME_FAMILY_STATUS        n
  &lt;chr&gt;                 &lt;int&gt;
1 Civil marriage        29775
2 Married              196432
3 Separated             19770
4 Single / not married  45444
5 Unknown                   2
6 Widow                 16088</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(NAME_INCOME_TYPE)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 2
  NAME_INCOME_TYPE          n
  &lt;chr&gt;                 &lt;int&gt;
1 Businessman              10
2 Commercial associate  71617
3 Maternity leave           5
4 Pensioner             55362
5 State servant         21703
6 Student                  18
7 Unemployed               22
8 Working              158774</code></pre>
</div>
</div>
<p>The categorical-value check identified a small number of unusual values. CODE_GENDER contains 4 records coded as XNA, while NAME_FAMILY_STATUS contains 2 records coded as Unknown. Because these values do not represent standard categories, they should be reviewed and handled explicitly during data preparation rather than automatically treated as valid categories. NAME_INCOME_TYPE also contains several rare categories, but these categories are interpretable and should be retained at this stage because low frequency alone does not indicate a data-quality problem.</p>
</section>
</section>
<section id="exploratory-results" class="level1">
<h1>Exploratory Results</h1>
<section id="how-common-is-payment-difficulty-in-the-training-data" class="level3">
<h3 class="anchored" data-anchor-id="how-common-is-payment-difficulty-in-the-training-data">How Common Is Payment Difficulty in the Training Data?</h3>
<p>The <code>TARGET</code> variable identifies whether an applicant experienced payment difficulties. Examining its distribution shows how common payment difficulty is in the training data and whether the outcome is balanced.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number and percentage of applicants by TARGET outcome</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>target_summary <span class="ot">&lt;-</span> application_train <span class="sc">|&gt;</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(TARGET) <span class="sc">|&gt;</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Percent =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>target_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  TARGET      n Percent
   &lt;dbl&gt;  &lt;int&gt;   &lt;dbl&gt;
1      0 282686   91.9 
2      1  24825    8.07</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the distribution of the TARGET outcome</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(target_summary, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(TARGET), <span class="at">y =</span> Percent)) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(<span class="fu">round</span>(Percent, <span class="dv">1</span>), <span class="st">"%"</span>)),</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Payment Difficulty in the Training Data"</span>,</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Payment Difficulty"</span>,</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Percentage of Applicants"</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>      <span class="st">"0"</span> <span class="ot">=</span> <span class="st">"No Payment Difficulty"</span>,</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>      <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"Payment Difficulty"</span></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="eda_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Payment difficulty is relatively uncommon in the training data. Approximately 8.1% of applicants experienced payment difficulty, while 91.9% did not. This creates a substantial class imbalance, meaning that a predictive model could appear accurate simply by favoring the much larger group without payment difficulty. Therefore, class imbalance should be considered when evaluating predictive models rather than relying only on overall accuracy.</p>
</section>
<section id="applicant-demographics" class="level2">
<h2 class="anchored" data-anchor-id="applicant-demographics">Applicant Demographics</h2>
<section id="how-does-applicant-age-differ-between-applicants-with-and-without-payment-difficulty" class="level3">
<h3 class="anchored" data-anchor-id="how-does-applicant-age-differ-between-applicants-with-and-without-payment-difficulty">How Does Applicant Age Differ Between Applicants With and Without Payment Difficulty?</h3>
<p>Applicant age is examined to determine whether payment difficulty varies across age groups. <code>DAYS_BIRTH</code> is converted to approximate age in years for easier interpretation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare applicant age by payment difficulty</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>age_summary <span class="ot">&lt;-</span> application_train <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Age =</span> <span class="sc">-</span>DAYS_BIRTH <span class="sc">/</span> <span class="fl">365.25</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TARGET) <span class="sc">|&gt;</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Applicants =</span> <span class="fu">n</span>(),</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Average_Age =</span> <span class="fu">mean</span>(Age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Median_Age =</span> <span class="fu">median</span>(Age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>age_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  TARGET Applicants Average_Age Median_Age
   &lt;dbl&gt;      &lt;int&gt;       &lt;dbl&gt;      &lt;dbl&gt;
1      0     282686        44.2       43.5
2      1      24825        40.8       39.1</code></pre>
</div>
</div>
<p>Applicants who experienced payment difficulty were younger on average than applicants who did not. The average age was approximately 40.8 years for applicants with payment difficulty compared with 44.2 years for applicants without payment difficulty. The median ages show a similar pattern, at 39.1 and 43.5 years, respectively. This suggests that age may be associated with payment difficulty and could be useful to examine further during modeling.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize age distribution by payment difficulty</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Age =</span> <span class="sc">-</span>DAYS_BIRTH <span class="sc">/</span> <span class="fl">365.25</span>,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Payment_Difficulty =</span> <span class="fu">factor</span>(</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>      TARGET,</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No Payment Difficulty"</span>, <span class="st">"Payment Difficulty"</span>)</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">fill =</span> Payment_Difficulty)) <span class="sc">+</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Age Distribution by Payment Difficulty"</span>,</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Applicant Age (Years)"</span>,</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Payment Difficulty"</span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="eda_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The age distributions show that applicants with payment difficulty tend to be younger than applicants without payment difficulty. The payment-difficulty group is more concentrated among younger applicants, while applicants without payment difficulty have relatively greater representation at older ages. This pattern is consistent with the difference in average age observed above and provides additional evidence that age may be useful as a potential predictor during modeling.</p>
</section>
<section id="how-do-income-and-requested-credit-amounts-differ-between-applicants-with-and-without-payment-difficulty" class="level3">
<h3 class="anchored" data-anchor-id="how-do-income-and-requested-credit-amounts-differ-between-applicants-with-and-without-payment-difficulty">How Do Income and Requested Credit Amounts Differ Between Applicants With and Without Payment Difficulty?</h3>
<p>Applicant income is examined to determine whether income differs between applicants who did and did not experience payment difficulties. Because unusually large income values were identified during the initial data checks, both the average and median are compared.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare income by payment difficulty</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>income_summary <span class="ot">&lt;-</span> application_train <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TARGET) <span class="sc">|&gt;</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Applicants =</span> <span class="fu">n</span>(),</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Average_Income =</span> <span class="fu">mean</span>(AMT_INCOME_TOTAL, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Median_Income =</span> <span class="fu">median</span>(AMT_INCOME_TOTAL, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>income_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  TARGET Applicants Average_Income Median_Income
   &lt;dbl&gt;      &lt;int&gt;          &lt;dbl&gt;         &lt;dbl&gt;
1      0     282686        169078.        148500
2      1      24825        165612.        135000</code></pre>
</div>
</div>
<p>Applicants who experienced payment difficulty had a lower median income than applicants without payment difficulty. The median income was 135,000 for applicants with payment difficulty compared with 148,500 for those without payment difficulty. The average incomes were more similar, which may partly reflect the influence of unusually large income values. This suggests that income may be associated with payment difficulty. Income should be retained as a potential predictor, while extreme income values should be examined during data preparation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare income distributions by payment difficulty</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Payment_Difficulty =</span> <span class="fu">factor</span>(</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>      TARGET,</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No Payment Difficulty"</span>, <span class="st">"Payment Difficulty"</span>)</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Payment_Difficulty, <span class="at">y =</span> AMT_INCOME_TOTAL)) <span class="sc">+</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>() <span class="sc">+</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Income Distribution by Payment Difficulty"</span>,</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Payment Difficulty"</span>,</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Applicant Income (Log Scale)"</span></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="eda_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The income distributions overlap considerably between the two groups, although applicants with payment difficulty have a somewhat lower median income. The plot also shows several extreme income values, including a particularly large outlier. These values should be examined during data preparation because they may influence summary statistics and later modeling.</p>
</section>
</section>
<section id="loan-characteristics" class="level2">
<h2 class="anchored" data-anchor-id="loan-characteristics">Loan Characteristics</h2>
<section id="how-do-requested-credit-amounts-differ-between-applicants-with-and-without-payment-difficulty" class="level3">
<h3 class="anchored" data-anchor-id="how-do-requested-credit-amounts-differ-between-applicants-with-and-without-payment-difficulty">How Do Requested Credit Amounts Differ Between Applicants With and Without Payment Difficulty?</h3>
<p>The amount of credit requested may be related to an applicant’s ability to repay the loan. Credit amounts are compared between applicants who did and did not experience payment difficulty.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare credit amount by payment difficulty</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>credit_summary <span class="ot">&lt;-</span> application_train <span class="sc">|&gt;</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TARGET) <span class="sc">|&gt;</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Applicants =</span> <span class="fu">n</span>(),</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Average_Credit =</span> <span class="fu">mean</span>(AMT_CREDIT, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Median_Credit =</span> <span class="fu">median</span>(AMT_CREDIT, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>credit_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  TARGET Applicants Average_Credit Median_Credit
   &lt;dbl&gt;      &lt;int&gt;          &lt;dbl&gt;         &lt;dbl&gt;
1      0     282686        602648.        517788
2      1      24825        557779.        497520</code></pre>
</div>
</div>
<p>Applicants with payment difficulty had a somewhat lower median requested credit amount than applicants without payment difficulty. The median credit amount was 497,520 for applicants with payment difficulty compared with 517,788 for those without payment difficulty. Although the difference is not large, it suggests that requested credit amount may contain some information related to payment difficulty. Therefore, credit amount should be retained and evaluated as a potential predictor during modeling.</p>
</section>
<section id="what-relationships-exist-among-key-financial-variables-such-as-income-credit-amount-and-annuity-amount" class="level3">
<h3 class="anchored" data-anchor-id="what-relationships-exist-among-key-financial-variables-such-as-income-credit-amount-and-annuity-amount">What Relationships Exist Among Key Financial Variables Such as Income, Credit Amount, and Annuity Amount?</h3>
<p>Income, credit amount, and loan annuity are examined together to determine whether these financial variables are strongly related. Strong relationships between predictors may be important to consider during later data preparation and modeling.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine correlations among key financial variables</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(AMT_INCOME_TOTAL, AMT_CREDIT, AMT_ANNUITY) <span class="sc">|&gt;</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>(<span class="at">use =</span> <span class="st">"complete.obs"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 AMT_INCOME_TOTAL AMT_CREDIT AMT_ANNUITY
AMT_INCOME_TOTAL        1.0000000  0.1568665   0.1916574
AMT_CREDIT              0.1568665  1.0000000   0.7701380
AMT_ANNUITY             0.1916574  0.7701380   1.0000000</code></pre>
</div>
</div>
<p>The financial variables show different levels of association with one another. AMT_CREDIT and AMT_ANNUITY have a relatively strong positive correlation of approximately 0.77, which is reasonable because larger loans generally require larger annuity payments. In contrast, applicant income has much weaker relationships with credit and annuity amounts. The strong relationship between credit and annuity suggests that these variables may contain overlapping information. Both should still be evaluated during modeling, but their relationship should be considered when assessing their predictive contribution.</p>
</section>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>The exploratory analysis identified several important characteristics and data-quality issues in the Home Credit application data. Payment difficulty occurs in approximately 8.1% of the training applications, creating a substantial class imbalance that should be considered when evaluating predictive models. Several housing and property variables contain more than 65% missing values and should be evaluated individually during data preparation to determine whether they provide enough information to retain or impute. Missingness in COMMONAREA_AVG was also associated with payment difficulty, with an 8.57% payment-difficulty rate when the value was missing compared with 6.91% when it was not missing. This suggests that missingness itself may contain useful predictive information. In addition, DAYS_EMPLOYED contains the special value 365243 for approximately 18.0% of applications and should be treated separately rather than as a valid employment duration.</p>
<p>The EDA also identified several variables that may contain useful information for predicting payment difficulty. Applicants with payment difficulty were younger on average, with an average age of 40.8 years compared with 44.2 years for applicants without payment difficulty. They also had a lower median income of 135,000 compared with 148,500 and a somewhat lower median requested credit amount of 497,520 compared with 517,788. These relationships do not establish causation, but they suggest that age, income, and credit characteristics should be evaluated as potential predictors during modeling. AMT_CREDIT and AMT_ANNUITY were also strongly positively correlated at approximately 0.77, indicating that they may contain overlapping information.</p>
<p>Overall, the EDA supports the business problem identified at the beginning of the project: payment difficulty appears to be associated with multiple aspects of an applicant’s financial and personal characteristics rather than a single variable. The analysis did not change the planned predictive-classification approach, but it clarified important data-preparation decisions and identified several variables and relationships that should be evaluated further during feature engineering and modeling.</p>
</section>
<section id="ai-use" class="level1">
<h1>AI Use</h1>
<p>ChatGPT was used to assist with developing and debugging R code, organizing the exploratory analysis, and improving the clarity of written interpretations. All code was run in Positron, and the resulting tables and visualizations were reviewed before conclusions were added to the notebook. AI was useful for generating and troubleshooting code, while reviewing the outputs was necessary to determine which findings were meaningful for the Home Credit business problem and what decisions should be carried forward into data preparation and modeling.</p>
<!-- -->

</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb39" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Home Credit Default Risk: Exploratory Data Analysis"</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Achuthasai Valluru"</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 3</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: false</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a><span class="fu"># Introduction</span></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>Home Credit provides consumer financing to customers who may have limited or no traditional credit history. The business problem is to distinguish applicants who are more likely to experience payment difficulties from applicants who are capable of repayment. Better identification of credit risk could help Home Credit reduce losses associated with payment difficulties while avoiding unnecessary rejection of applicants who are likely to repay.</span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>The purpose of this exploratory data analysis is to understand the application data, identify data-quality issues that may affect later modeling, and investigate applicant characteristics that may be associated with payment difficulty.</span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a><span class="fu">## EDA Questions</span></span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>The analysis will address the following questions:</span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>How common is payment difficulty in the training data?</span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>How does applicant age differ between applicants with and without payment difficulty?</span>
<span id="cb39-25"><a href="#cb39-25" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>How do income and requested credit amounts differ between applicants with and without payment difficulty?</span>
<span id="cb39-26"><a href="#cb39-26" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>What relationships exist among key financial variables such as income, credit amount, and annuity amount?</span>
<span id="cb39-27"><a href="#cb39-27" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>Which variables contain substantial missing data, unusual values, or other data-quality problems that must be addressed before modeling?</span>
<span id="cb39-28"><a href="#cb39-28" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>Are the training and test datasets structurally consistent enough to support the planned predictive analysis?</span>
<span id="cb39-29"><a href="#cb39-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-30"><a href="#cb39-30" aria-hidden="true" tabindex="-1"></a><span class="fu"># Description of the Data</span></span>
<span id="cb39-33"><a href="#cb39-33" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-34"><a href="#cb39-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages used for data manipulation and visualization</span></span>
<span id="cb39-35"><a href="#cb39-35" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb39-36"><a href="#cb39-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-37"><a href="#cb39-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the required Home Credit application datasets</span></span>
<span id="cb39-38"><a href="#cb39-38" aria-hidden="true" tabindex="-1"></a>application_train <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Data/application_train.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb39-39"><a href="#cb39-39" aria-hidden="true" tabindex="-1"></a>application_test <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Data/application_test.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb39-40"><a href="#cb39-40" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-41"><a href="#cb39-41" aria-hidden="true" tabindex="-1"></a><span class="fu">## Dataset Dimensions</span></span>
<span id="cb39-42"><a href="#cb39-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-43"><a href="#cb39-43" aria-hidden="true" tabindex="-1"></a>The first step is to examine the size of the training and test datasets.</span>
<span id="cb39-44"><a href="#cb39-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-47"><a href="#cb39-47" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-48"><a href="#cb39-48" aria-hidden="true" tabindex="-1"></a><span class="co"># Report the number of rows and columns in each application dataset</span></span>
<span id="cb39-49"><a href="#cb39-49" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb39-50"><a href="#cb39-50" aria-hidden="true" tabindex="-1"></a>  <span class="at">Dataset =</span> <span class="fu">c</span>(<span class="st">"Training"</span>, <span class="st">"Test"</span>),</span>
<span id="cb39-51"><a href="#cb39-51" aria-hidden="true" tabindex="-1"></a>  <span class="at">Rows =</span> <span class="fu">c</span>(<span class="fu">nrow</span>(application_train), <span class="fu">nrow</span>(application_test)),</span>
<span id="cb39-52"><a href="#cb39-52" aria-hidden="true" tabindex="-1"></a>  <span class="at">Columns =</span> <span class="fu">c</span>(<span class="fu">ncol</span>(application_train), <span class="fu">ncol</span>(application_test))</span>
<span id="cb39-53"><a href="#cb39-53" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-54"><a href="#cb39-54" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-55"><a href="#cb39-55" aria-hidden="true" tabindex="-1"></a>The training dataset contains 307,511 applications and 122 variables, while the test dataset contains 48,744 applications and 121 variables. The one-column difference is expected because the training data contain the <span class="in">`TARGET`</span> variable indicating whether an applicant experienced payment difficulty, while the test data require this outcome to be predicted. Before modeling, the remaining variables should be checked to confirm that the training and test datasets have consistent structures.</span>
<span id="cb39-56"><a href="#cb39-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-57"><a href="#cb39-57" aria-hidden="true" tabindex="-1"></a><span class="fu">## Training and Test Structure</span></span>
<span id="cb39-58"><a href="#cb39-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-59"><a href="#cb39-59" aria-hidden="true" tabindex="-1"></a>Because the training dataset contains one additional column, the column names are compared to determine whether <span class="in">`TARGET`</span> is the only structural difference.</span>
<span id="cb39-60"><a href="#cb39-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-63"><a href="#cb39-63" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-64"><a href="#cb39-64" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify columns that appear in only one of the two application datasets</span></span>
<span id="cb39-65"><a href="#cb39-65" aria-hidden="true" tabindex="-1"></a>train_only <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(<span class="fu">names</span>(application_train), <span class="fu">names</span>(application_test))</span>
<span id="cb39-66"><a href="#cb39-66" aria-hidden="true" tabindex="-1"></a>test_only <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(<span class="fu">names</span>(application_test), <span class="fu">names</span>(application_train))</span>
<span id="cb39-67"><a href="#cb39-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-68"><a href="#cb39-68" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb39-69"><a href="#cb39-69" aria-hidden="true" tabindex="-1"></a>  <span class="at">Comparison =</span> <span class="fu">c</span>(<span class="st">"Training only"</span>, <span class="st">"Test only"</span>),</span>
<span id="cb39-70"><a href="#cb39-70" aria-hidden="true" tabindex="-1"></a>  <span class="at">Columns =</span> <span class="fu">c</span>(</span>
<span id="cb39-71"><a href="#cb39-71" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste</span>(train_only, <span class="at">collapse =</span> <span class="st">", "</span>),</span>
<span id="cb39-72"><a href="#cb39-72" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste</span>(test_only, <span class="at">collapse =</span> <span class="st">", "</span>)</span>
<span id="cb39-73"><a href="#cb39-73" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb39-74"><a href="#cb39-74" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-75"><a href="#cb39-75" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-76"><a href="#cb39-76" aria-hidden="true" tabindex="-1"></a>The comparison confirms that TARGET is the only column present in the training data but absent from the test data. All predictor columns are shared between the two datasets. This is the expected structure for a supervised prediction problem: the training data provide known outcomes for model development, while the test data contain the same applicant information without the outcome. Therefore, no predictor columns need to be reconciled between the two datasets based on column names.</span>
<span id="cb39-77"><a href="#cb39-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-78"><a href="#cb39-78" aria-hidden="true" tabindex="-1"></a><span class="fu">## Grain and Primary Key</span></span>
<span id="cb39-79"><a href="#cb39-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-80"><a href="#cb39-80" aria-hidden="true" tabindex="-1"></a>The application datasets are expected to contain one row per loan application. The uniqueness of <span class="in">`SK_ID_CURR`</span> is checked to determine whether it can serve as the primary key.</span>
<span id="cb39-83"><a href="#cb39-83" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-84"><a href="#cb39-84" aria-hidden="true" tabindex="-1"></a><span class="co"># Check whether SK_ID_CURR uniquely identifies each row in the application datasets</span></span>
<span id="cb39-85"><a href="#cb39-85" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb39-86"><a href="#cb39-86" aria-hidden="true" tabindex="-1"></a>  <span class="at">Dataset =</span> <span class="fu">c</span>(<span class="st">"Training"</span>, <span class="st">"Test"</span>),</span>
<span id="cb39-87"><a href="#cb39-87" aria-hidden="true" tabindex="-1"></a>  <span class="at">Rows =</span> <span class="fu">c</span>(<span class="fu">nrow</span>(application_train), <span class="fu">nrow</span>(application_test)),</span>
<span id="cb39-88"><a href="#cb39-88" aria-hidden="true" tabindex="-1"></a>  <span class="at">Unique_SK_ID_CURR =</span> <span class="fu">c</span>(</span>
<span id="cb39-89"><a href="#cb39-89" aria-hidden="true" tabindex="-1"></a>    <span class="fu">n_distinct</span>(application_train<span class="sc">$</span>SK_ID_CURR),</span>
<span id="cb39-90"><a href="#cb39-90" aria-hidden="true" tabindex="-1"></a>    <span class="fu">n_distinct</span>(application_test<span class="sc">$</span>SK_ID_CURR)</span>
<span id="cb39-91"><a href="#cb39-91" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb39-92"><a href="#cb39-92" aria-hidden="true" tabindex="-1"></a>  <span class="at">Duplicate_SK_ID_CURR =</span> <span class="fu">c</span>(</span>
<span id="cb39-93"><a href="#cb39-93" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sum</span>(<span class="fu">duplicated</span>(application_train<span class="sc">$</span>SK_ID_CURR)),</span>
<span id="cb39-94"><a href="#cb39-94" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sum</span>(<span class="fu">duplicated</span>(application_test<span class="sc">$</span>SK_ID_CURR))</span>
<span id="cb39-95"><a href="#cb39-95" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb39-96"><a href="#cb39-96" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-97"><a href="#cb39-97" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-98"><a href="#cb39-98" aria-hidden="true" tabindex="-1"></a>The number of unique SK_ID_CURR values equals the number of rows in both datasets, and no duplicate identifiers were found. This confirms that SK_ID_CURR uniquely identifies each application record in both the training and test data. For this analysis, the application tables therefore have a grain of one row per current loan application, with SK_ID_CURR serving as the primary key. No duplicate application records need to be removed based on this identifier.</span>
<span id="cb39-99"><a href="#cb39-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-100"><a href="#cb39-100" aria-hidden="true" tabindex="-1"></a><span class="fu">## Variable Groups</span></span>
<span id="cb39-101"><a href="#cb39-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-102"><a href="#cb39-102" aria-hidden="true" tabindex="-1"></a>The application datasets contain many variables describing different aspects of an applicant and the requested loan. The Home Credit data dictionary is used to better understand the meaning of these variables and organize the information available for exploratory analysis.</span>
<span id="cb39-103"><a href="#cb39-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-106"><a href="#cb39-106" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-107"><a href="#cb39-107" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the Home Credit data dictionary</span></span>
<span id="cb39-108"><a href="#cb39-108" aria-hidden="true" tabindex="-1"></a>column_description <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb39-109"><a href="#cb39-109" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Data/HomeCredit_columns_description.csv"</span>,</span>
<span id="cb39-110"><a href="#cb39-110" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb39-111"><a href="#cb39-111" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-112"><a href="#cb39-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-113"><a href="#cb39-113" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview the structure of the data dictionary</span></span>
<span id="cb39-114"><a href="#cb39-114" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(column_description)</span>
<span id="cb39-115"><a href="#cb39-115" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-116"><a href="#cb39-116" aria-hidden="true" tabindex="-1"></a>Based on the data dictionary, the application data include several major groups of information that may be useful for understanding payment difficulty. These include applicant demographics and household characteristics, employment and income information, loan and annuity characteristics, housing and property information, external credit scores, contact and document indicators, regional information, and credit bureau inquiry information. The TARGET variable is the outcome in the training data and indicates whether an applicant experienced payment difficulties. These groups provide different perspectives on an applicant's financial situation and may contain useful predictors of repayment risk.</span>
<span id="cb39-117"><a href="#cb39-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-118"><a href="#cb39-118" aria-hidden="true" tabindex="-1"></a><span class="fu"># Data Integrity</span></span>
<span id="cb39-119"><a href="#cb39-119" aria-hidden="true" tabindex="-1"></a><span class="fu">### Which Variables Contain Substantial Missing Data?</span></span>
<span id="cb39-120"><a href="#cb39-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-121"><a href="#cb39-121" aria-hidden="true" tabindex="-1"></a>Missing data can affect both exploratory analysis and later predictive modeling. The training data are examined to identify variables with substantial missingness and determine which variables may require special treatment during data preparation.</span>
<span id="cb39-122"><a href="#cb39-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-125"><a href="#cb39-125" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-126"><a href="#cb39-126" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number and percentage of missing values for each variable</span></span>
<span id="cb39-127"><a href="#cb39-127" aria-hidden="true" tabindex="-1"></a>missing_summary <span class="ot">&lt;-</span> application_train <span class="sc">|&gt;</span></span>
<span id="cb39-128"><a href="#cb39-128" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)))) <span class="sc">|&gt;</span></span>
<span id="cb39-129"><a href="#cb39-129" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb39-130"><a href="#cb39-130" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb39-131"><a href="#cb39-131" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"Variable"</span>,</span>
<span id="cb39-132"><a href="#cb39-132" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"Missing"</span></span>
<span id="cb39-133"><a href="#cb39-133" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb39-134"><a href="#cb39-134" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb39-135"><a href="#cb39-135" aria-hidden="true" tabindex="-1"></a>    <span class="at">Percent_Missing =</span> Missing <span class="sc">/</span> <span class="fu">nrow</span>(application_train) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb39-136"><a href="#cb39-136" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb39-137"><a href="#cb39-137" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Percent_Missing))</span>
<span id="cb39-138"><a href="#cb39-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-139"><a href="#cb39-139" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the variables with the highest percentages of missing values</span></span>
<span id="cb39-140"><a href="#cb39-140" aria-hidden="true" tabindex="-1"></a>missing_summary <span class="sc">|&gt;</span></span>
<span id="cb39-141"><a href="#cb39-141" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">15</span>)</span>
<span id="cb39-142"><a href="#cb39-142" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-143"><a href="#cb39-143" aria-hidden="true" tabindex="-1"></a>The missing-value analysis shows substantial missingness in several variables, particularly those describing housing and property characteristics. COMMONAREA_AVG, COMMONAREA_MODE, and COMMONAREA_MEDI each have approximately 69.9% missing values, while several apartment, floor, and building-related variables are missing for more than 65% of applications. Because these variables are unavailable for a large portion of applicants, relying heavily on them could reduce the amount of usable information available for consistent default-risk prediction. During data preparation, variables with very high missingness should be evaluated individually to determine whether they provide enough useful information to retain or impute; otherwise, they may be excluded from modeling.</span>
<span id="cb39-144"><a href="#cb39-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-147"><a href="#cb39-147" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-148"><a href="#cb39-148" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine whether missingness in a highly incomplete variable is associated with payment difficulty</span></span>
<span id="cb39-149"><a href="#cb39-149" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb39-150"><a href="#cb39-150" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb39-151"><a href="#cb39-151" aria-hidden="true" tabindex="-1"></a>    <span class="at">COMMONAREA_AVG_Missing =</span> <span class="fu">if_else</span>(<span class="fu">is.na</span>(COMMONAREA_AVG), <span class="st">"Missing"</span>, <span class="st">"Not Missing"</span>)</span>
<span id="cb39-152"><a href="#cb39-152" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb39-153"><a href="#cb39-153" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(COMMONAREA_AVG_Missing) <span class="sc">|&gt;</span></span>
<span id="cb39-154"><a href="#cb39-154" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb39-155"><a href="#cb39-155" aria-hidden="true" tabindex="-1"></a>    <span class="at">Applicants =</span> <span class="fu">n</span>(),</span>
<span id="cb39-156"><a href="#cb39-156" aria-hidden="true" tabindex="-1"></a>    <span class="at">Payment_Difficulty_Rate =</span> <span class="fu">mean</span>(TARGET) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb39-157"><a href="#cb39-157" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb39-158"><a href="#cb39-158" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb39-159"><a href="#cb39-159" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-160"><a href="#cb39-160" aria-hidden="true" tabindex="-1"></a>Applicants with missing <span class="in">`COMMONAREA_AVG`</span> values had a payment-difficulty rate of 8.57%, compared with 6.91% among applicants with non-missing values. This suggests that missingness in this variable is associated with payment difficulty and may contain useful predictive information rather than being purely random. Therefore, during data preparation, the missing values should not simply be ignored or the affected records automatically removed. The variable and its missingness should be evaluated as potential information for the predictive model.</span>
<span id="cb39-161"><a href="#cb39-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-162"><a href="#cb39-162" aria-hidden="true" tabindex="-1"></a><span class="fu">### Are There Unusual Numeric Values That Could Affect the Analysis?</span></span>
<span id="cb39-163"><a href="#cb39-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-164"><a href="#cb39-164" aria-hidden="true" tabindex="-1"></a>Several variables represent applicant characteristics and time measurements. Selected variables are examined for unusual or potentially unrealistic values that could affect interpretation or later modeling.</span>
<span id="cb39-165"><a href="#cb39-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-168"><a href="#cb39-168" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-169"><a href="#cb39-169" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine ranges for selected numeric variables</span></span>
<span id="cb39-170"><a href="#cb39-170" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb39-171"><a href="#cb39-171" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb39-172"><a href="#cb39-172" aria-hidden="true" tabindex="-1"></a>    <span class="at">Min_Days_Birth =</span> <span class="fu">min</span>(DAYS_BIRTH, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb39-173"><a href="#cb39-173" aria-hidden="true" tabindex="-1"></a>    <span class="at">Max_Days_Birth =</span> <span class="fu">max</span>(DAYS_BIRTH, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb39-174"><a href="#cb39-174" aria-hidden="true" tabindex="-1"></a>    <span class="at">Min_Days_Employed =</span> <span class="fu">min</span>(DAYS_EMPLOYED, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb39-175"><a href="#cb39-175" aria-hidden="true" tabindex="-1"></a>    <span class="at">Max_Days_Employed =</span> <span class="fu">max</span>(DAYS_EMPLOYED, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb39-176"><a href="#cb39-176" aria-hidden="true" tabindex="-1"></a>    <span class="at">Min_Income =</span> <span class="fu">min</span>(AMT_INCOME_TOTAL, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb39-177"><a href="#cb39-177" aria-hidden="true" tabindex="-1"></a>    <span class="at">Max_Income =</span> <span class="fu">max</span>(AMT_INCOME_TOTAL, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb39-178"><a href="#cb39-178" aria-hidden="true" tabindex="-1"></a>    <span class="at">Min_Credit =</span> <span class="fu">min</span>(AMT_CREDIT, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb39-179"><a href="#cb39-179" aria-hidden="true" tabindex="-1"></a>    <span class="at">Max_Credit =</span> <span class="fu">max</span>(AMT_CREDIT, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-180"><a href="#cb39-180" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb39-181"><a href="#cb39-181" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-184"><a href="#cb39-184" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-185"><a href="#cb39-185" aria-hidden="true" tabindex="-1"></a><span class="co"># Investigate the unusual DAYS_EMPLOYED value</span></span>
<span id="cb39-186"><a href="#cb39-186" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb39-187"><a href="#cb39-187" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb39-188"><a href="#cb39-188" aria-hidden="true" tabindex="-1"></a>    <span class="at">Records_365243 =</span> <span class="fu">sum</span>(DAYS_EMPLOYED <span class="sc">==</span> <span class="dv">365243</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb39-189"><a href="#cb39-189" aria-hidden="true" tabindex="-1"></a>    <span class="at">Percent_365243 =</span> <span class="fu">mean</span>(DAYS_EMPLOYED <span class="sc">==</span> <span class="dv">365243</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb39-190"><a href="#cb39-190" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb39-191"><a href="#cb39-191" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-192"><a href="#cb39-192" aria-hidden="true" tabindex="-1"></a>The value 365243 appears in 55,374 records, representing approximately 18.0% of the training data. This is not a realistic number of employment days and appears to represent a special value rather than an actual employment duration. During data preparation, this value should therefore be treated separately rather than as a valid number of employment days so that it does not distort the relationship between employment history and payment difficulty.</span>
<span id="cb39-193"><a href="#cb39-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-194"><a href="#cb39-194" aria-hidden="true" tabindex="-1"></a><span class="fu">### Does DAYS_BIRTH Contain Unrealistic Applicant Ages?</span></span>
<span id="cb39-195"><a href="#cb39-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-196"><a href="#cb39-196" aria-hidden="true" tabindex="-1"></a><span class="in">`DAYS_BIRTH`</span> contains negative values because age is recorded as the number of days before the current loan application. Converting these values to approximate ages will make the range easier to interpret.</span>
<span id="cb39-197"><a href="#cb39-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-200"><a href="#cb39-200" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-201"><a href="#cb39-201" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert DAYS_BIRTH to approximate age in years and examine the range</span></span>
<span id="cb39-202"><a href="#cb39-202" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb39-203"><a href="#cb39-203" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb39-204"><a href="#cb39-204" aria-hidden="true" tabindex="-1"></a>    <span class="at">Min_Age =</span> <span class="fu">min</span>(<span class="sc">-</span>DAYS_BIRTH <span class="sc">/</span> <span class="fl">365.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb39-205"><a href="#cb39-205" aria-hidden="true" tabindex="-1"></a>    <span class="at">Max_Age =</span> <span class="fu">max</span>(<span class="sc">-</span>DAYS_BIRTH <span class="sc">/</span> <span class="fl">365.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb39-206"><a href="#cb39-206" aria-hidden="true" tabindex="-1"></a>    <span class="at">Average_Age =</span> <span class="fu">mean</span>(<span class="sc">-</span>DAYS_BIRTH <span class="sc">/</span> <span class="fl">365.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-207"><a href="#cb39-207" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb39-208"><a href="#cb39-208" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-209"><a href="#cb39-209" aria-hidden="true" tabindex="-1"></a>  After converting DAYS_BIRTH from days to approximate years, applicant ages range from 20.5 to 69.1 years, with an average age of 43.9 years. These values appear reasonable for loan applicants. Therefore, the negative values in DAYS_BIRTH reflect how the variable is recorded rather than a data-quality problem.</span>
<span id="cb39-210"><a href="#cb39-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-211"><a href="#cb39-211" aria-hidden="true" tabindex="-1"></a><span class="fu">### Are There Unusual Values in the Categorical Variables?</span></span>
<span id="cb39-212"><a href="#cb39-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-213"><a href="#cb39-213" aria-hidden="true" tabindex="-1"></a>Selected categorical variables are examined to identify unusual or unexpected category values that may require cleaning before modeling.</span>
<span id="cb39-214"><a href="#cb39-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-217"><a href="#cb39-217" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-218"><a href="#cb39-218" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine values in selected categorical variables</span></span>
<span id="cb39-219"><a href="#cb39-219" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb39-220"><a href="#cb39-220" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(CODE_GENDER)</span>
<span id="cb39-221"><a href="#cb39-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-222"><a href="#cb39-222" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb39-223"><a href="#cb39-223" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(NAME_FAMILY_STATUS)</span>
<span id="cb39-224"><a href="#cb39-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-225"><a href="#cb39-225" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb39-226"><a href="#cb39-226" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(NAME_INCOME_TYPE)</span>
<span id="cb39-227"><a href="#cb39-227" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-228"><a href="#cb39-228" aria-hidden="true" tabindex="-1"></a>The categorical-value check identified a small number of unusual values. CODE_GENDER contains 4 records coded as XNA, while NAME_FAMILY_STATUS contains 2 records coded as Unknown. Because these values do not represent standard categories, they should be reviewed and handled explicitly during data preparation rather than automatically treated as valid categories. NAME_INCOME_TYPE also contains several rare categories, but these categories are interpretable and should be retained at this stage because low frequency alone does not indicate a data-quality problem.</span>
<span id="cb39-229"><a href="#cb39-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-230"><a href="#cb39-230" aria-hidden="true" tabindex="-1"></a><span class="fu"># Exploratory Results</span></span>
<span id="cb39-231"><a href="#cb39-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-232"><a href="#cb39-232" aria-hidden="true" tabindex="-1"></a><span class="fu">### How Common Is Payment Difficulty in the Training Data?</span></span>
<span id="cb39-233"><a href="#cb39-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-234"><a href="#cb39-234" aria-hidden="true" tabindex="-1"></a>The <span class="in">`TARGET`</span> variable identifies whether an applicant experienced payment difficulties. Examining its distribution shows how common payment difficulty is in the training data and whether the outcome is balanced.</span>
<span id="cb39-235"><a href="#cb39-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-238"><a href="#cb39-238" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-239"><a href="#cb39-239" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number and percentage of applicants by TARGET outcome</span></span>
<span id="cb39-240"><a href="#cb39-240" aria-hidden="true" tabindex="-1"></a>target_summary <span class="ot">&lt;-</span> application_train <span class="sc">|&gt;</span></span>
<span id="cb39-241"><a href="#cb39-241" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(TARGET) <span class="sc">|&gt;</span></span>
<span id="cb39-242"><a href="#cb39-242" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb39-243"><a href="#cb39-243" aria-hidden="true" tabindex="-1"></a>    <span class="at">Percent =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb39-244"><a href="#cb39-244" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb39-245"><a href="#cb39-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-246"><a href="#cb39-246" aria-hidden="true" tabindex="-1"></a>target_summary</span>
<span id="cb39-247"><a href="#cb39-247" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-250"><a href="#cb39-250" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-251"><a href="#cb39-251" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the distribution of the TARGET outcome</span></span>
<span id="cb39-252"><a href="#cb39-252" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(target_summary, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(TARGET), <span class="at">y =</span> Percent)) <span class="sc">+</span></span>
<span id="cb39-253"><a href="#cb39-253" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb39-254"><a href="#cb39-254" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb39-255"><a href="#cb39-255" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(<span class="fu">round</span>(Percent, <span class="dv">1</span>), <span class="st">"%"</span>)),</span>
<span id="cb39-256"><a href="#cb39-256" aria-hidden="true" tabindex="-1"></a>    <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span></span>
<span id="cb39-257"><a href="#cb39-257" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb39-258"><a href="#cb39-258" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb39-259"><a href="#cb39-259" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Payment Difficulty in the Training Data"</span>,</span>
<span id="cb39-260"><a href="#cb39-260" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Payment Difficulty"</span>,</span>
<span id="cb39-261"><a href="#cb39-261" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Percentage of Applicants"</span></span>
<span id="cb39-262"><a href="#cb39-262" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb39-263"><a href="#cb39-263" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(</span>
<span id="cb39-264"><a href="#cb39-264" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(</span>
<span id="cb39-265"><a href="#cb39-265" aria-hidden="true" tabindex="-1"></a>      <span class="st">"0"</span> <span class="ot">=</span> <span class="st">"No Payment Difficulty"</span>,</span>
<span id="cb39-266"><a href="#cb39-266" aria-hidden="true" tabindex="-1"></a>      <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"Payment Difficulty"</span></span>
<span id="cb39-267"><a href="#cb39-267" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb39-268"><a href="#cb39-268" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb39-269"><a href="#cb39-269" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb39-270"><a href="#cb39-270" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-271"><a href="#cb39-271" aria-hidden="true" tabindex="-1"></a>Payment difficulty is relatively uncommon in the training data. Approximately 8.1% of applicants experienced payment difficulty, while 91.9% did not. This creates a substantial class imbalance, meaning that a predictive model could appear accurate simply by favoring the much larger group without payment difficulty. Therefore, class imbalance should be considered when evaluating predictive models rather than relying only on overall accuracy.</span>
<span id="cb39-272"><a href="#cb39-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-273"><a href="#cb39-273" aria-hidden="true" tabindex="-1"></a><span class="fu">## Applicant Demographics</span></span>
<span id="cb39-274"><a href="#cb39-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-275"><a href="#cb39-275" aria-hidden="true" tabindex="-1"></a><span class="fu">### How Does Applicant Age Differ Between Applicants With and Without Payment Difficulty?</span></span>
<span id="cb39-276"><a href="#cb39-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-277"><a href="#cb39-277" aria-hidden="true" tabindex="-1"></a>Applicant age is examined to determine whether payment difficulty varies across age groups. <span class="in">`DAYS_BIRTH`</span> is converted to approximate age in years for easier interpretation.</span>
<span id="cb39-278"><a href="#cb39-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-281"><a href="#cb39-281" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-282"><a href="#cb39-282" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare applicant age by payment difficulty</span></span>
<span id="cb39-283"><a href="#cb39-283" aria-hidden="true" tabindex="-1"></a>age_summary <span class="ot">&lt;-</span> application_train <span class="sc">|&gt;</span></span>
<span id="cb39-284"><a href="#cb39-284" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb39-285"><a href="#cb39-285" aria-hidden="true" tabindex="-1"></a>    <span class="at">Age =</span> <span class="sc">-</span>DAYS_BIRTH <span class="sc">/</span> <span class="fl">365.25</span></span>
<span id="cb39-286"><a href="#cb39-286" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb39-287"><a href="#cb39-287" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TARGET) <span class="sc">|&gt;</span></span>
<span id="cb39-288"><a href="#cb39-288" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb39-289"><a href="#cb39-289" aria-hidden="true" tabindex="-1"></a>    <span class="at">Applicants =</span> <span class="fu">n</span>(),</span>
<span id="cb39-290"><a href="#cb39-290" aria-hidden="true" tabindex="-1"></a>    <span class="at">Average_Age =</span> <span class="fu">mean</span>(Age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb39-291"><a href="#cb39-291" aria-hidden="true" tabindex="-1"></a>    <span class="at">Median_Age =</span> <span class="fu">median</span>(Age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-292"><a href="#cb39-292" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb39-293"><a href="#cb39-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-294"><a href="#cb39-294" aria-hidden="true" tabindex="-1"></a>age_summary</span>
<span id="cb39-295"><a href="#cb39-295" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-296"><a href="#cb39-296" aria-hidden="true" tabindex="-1"></a>Applicants who experienced payment difficulty were younger on average than applicants who did not. The average age was approximately 40.8 years for applicants with payment difficulty compared with 44.2 years for applicants without payment difficulty. The median ages show a similar pattern, at 39.1 and 43.5 years, respectively. This suggests that age may be associated with payment difficulty and could be useful to examine further during modeling.</span>
<span id="cb39-299"><a href="#cb39-299" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-300"><a href="#cb39-300" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize age distribution by payment difficulty</span></span>
<span id="cb39-301"><a href="#cb39-301" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb39-302"><a href="#cb39-302" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb39-303"><a href="#cb39-303" aria-hidden="true" tabindex="-1"></a>    <span class="at">Age =</span> <span class="sc">-</span>DAYS_BIRTH <span class="sc">/</span> <span class="fl">365.25</span>,</span>
<span id="cb39-304"><a href="#cb39-304" aria-hidden="true" tabindex="-1"></a>    <span class="at">Payment_Difficulty =</span> <span class="fu">factor</span>(</span>
<span id="cb39-305"><a href="#cb39-305" aria-hidden="true" tabindex="-1"></a>      TARGET,</span>
<span id="cb39-306"><a href="#cb39-306" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb39-307"><a href="#cb39-307" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No Payment Difficulty"</span>, <span class="st">"Payment Difficulty"</span>)</span>
<span id="cb39-308"><a href="#cb39-308" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb39-309"><a href="#cb39-309" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb39-310"><a href="#cb39-310" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">fill =</span> Payment_Difficulty)) <span class="sc">+</span></span>
<span id="cb39-311"><a href="#cb39-311" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb39-312"><a href="#cb39-312" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb39-313"><a href="#cb39-313" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Age Distribution by Payment Difficulty"</span>,</span>
<span id="cb39-314"><a href="#cb39-314" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Applicant Age (Years)"</span>,</span>
<span id="cb39-315"><a href="#cb39-315" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb39-316"><a href="#cb39-316" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Payment Difficulty"</span></span>
<span id="cb39-317"><a href="#cb39-317" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb39-318"><a href="#cb39-318" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb39-319"><a href="#cb39-319" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-320"><a href="#cb39-320" aria-hidden="true" tabindex="-1"></a>The age distributions show that applicants with payment difficulty tend to be younger than applicants without payment difficulty. The payment-difficulty group is more concentrated among younger applicants, while applicants without payment difficulty have relatively greater representation at older ages. This pattern is consistent with the difference in average age observed above and provides additional evidence that age may be useful as a potential predictor during modeling.</span>
<span id="cb39-321"><a href="#cb39-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-322"><a href="#cb39-322" aria-hidden="true" tabindex="-1"></a><span class="fu">### How Do Income and Requested Credit Amounts Differ Between Applicants With and Without Payment Difficulty?</span></span>
<span id="cb39-323"><a href="#cb39-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-324"><a href="#cb39-324" aria-hidden="true" tabindex="-1"></a>Applicant income is examined to determine whether income differs between applicants who did and did not experience payment difficulties. Because unusually large income values were identified during the initial data checks, both the average and median are compared.</span>
<span id="cb39-327"><a href="#cb39-327" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-328"><a href="#cb39-328" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare income by payment difficulty</span></span>
<span id="cb39-329"><a href="#cb39-329" aria-hidden="true" tabindex="-1"></a>income_summary <span class="ot">&lt;-</span> application_train <span class="sc">|&gt;</span></span>
<span id="cb39-330"><a href="#cb39-330" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TARGET) <span class="sc">|&gt;</span></span>
<span id="cb39-331"><a href="#cb39-331" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb39-332"><a href="#cb39-332" aria-hidden="true" tabindex="-1"></a>    <span class="at">Applicants =</span> <span class="fu">n</span>(),</span>
<span id="cb39-333"><a href="#cb39-333" aria-hidden="true" tabindex="-1"></a>    <span class="at">Average_Income =</span> <span class="fu">mean</span>(AMT_INCOME_TOTAL, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb39-334"><a href="#cb39-334" aria-hidden="true" tabindex="-1"></a>    <span class="at">Median_Income =</span> <span class="fu">median</span>(AMT_INCOME_TOTAL, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-335"><a href="#cb39-335" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb39-336"><a href="#cb39-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-337"><a href="#cb39-337" aria-hidden="true" tabindex="-1"></a>income_summary</span>
<span id="cb39-338"><a href="#cb39-338" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-339"><a href="#cb39-339" aria-hidden="true" tabindex="-1"></a>Applicants who experienced payment difficulty had a lower median income than applicants without payment difficulty. The median income was 135,000 for applicants with payment difficulty compared with 148,500 for those without payment difficulty. The average incomes were more similar, which may partly reflect the influence of unusually large income values. This suggests that income may be associated with payment difficulty. Income should be retained as a potential predictor, while extreme income values should be examined during data preparation.</span>
<span id="cb39-342"><a href="#cb39-342" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-343"><a href="#cb39-343" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare income distributions by payment difficulty</span></span>
<span id="cb39-344"><a href="#cb39-344" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb39-345"><a href="#cb39-345" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb39-346"><a href="#cb39-346" aria-hidden="true" tabindex="-1"></a>    <span class="at">Payment_Difficulty =</span> <span class="fu">factor</span>(</span>
<span id="cb39-347"><a href="#cb39-347" aria-hidden="true" tabindex="-1"></a>      TARGET,</span>
<span id="cb39-348"><a href="#cb39-348" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb39-349"><a href="#cb39-349" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No Payment Difficulty"</span>, <span class="st">"Payment Difficulty"</span>)</span>
<span id="cb39-350"><a href="#cb39-350" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb39-351"><a href="#cb39-351" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb39-352"><a href="#cb39-352" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Payment_Difficulty, <span class="at">y =</span> AMT_INCOME_TOTAL)) <span class="sc">+</span></span>
<span id="cb39-353"><a href="#cb39-353" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb39-354"><a href="#cb39-354" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>() <span class="sc">+</span></span>
<span id="cb39-355"><a href="#cb39-355" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb39-356"><a href="#cb39-356" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Income Distribution by Payment Difficulty"</span>,</span>
<span id="cb39-357"><a href="#cb39-357" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Payment Difficulty"</span>,</span>
<span id="cb39-358"><a href="#cb39-358" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Applicant Income (Log Scale)"</span></span>
<span id="cb39-359"><a href="#cb39-359" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb39-360"><a href="#cb39-360" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb39-361"><a href="#cb39-361" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-362"><a href="#cb39-362" aria-hidden="true" tabindex="-1"></a>The income distributions overlap considerably between the two groups, although applicants with payment difficulty have a somewhat lower median income. The plot also shows several extreme income values, including a particularly large outlier. These values should be examined during data preparation because they may influence summary statistics and later modeling.</span>
<span id="cb39-363"><a href="#cb39-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-364"><a href="#cb39-364" aria-hidden="true" tabindex="-1"></a><span class="fu">## Loan Characteristics</span></span>
<span id="cb39-365"><a href="#cb39-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-366"><a href="#cb39-366" aria-hidden="true" tabindex="-1"></a><span class="fu">### How Do Requested Credit Amounts Differ Between Applicants With and Without Payment Difficulty?</span></span>
<span id="cb39-367"><a href="#cb39-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-368"><a href="#cb39-368" aria-hidden="true" tabindex="-1"></a>The amount of credit requested may be related to an applicant's ability to repay the loan. Credit amounts are compared between applicants who did and did not experience payment difficulty.</span>
<span id="cb39-371"><a href="#cb39-371" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-372"><a href="#cb39-372" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare credit amount by payment difficulty</span></span>
<span id="cb39-373"><a href="#cb39-373" aria-hidden="true" tabindex="-1"></a>credit_summary <span class="ot">&lt;-</span> application_train <span class="sc">|&gt;</span></span>
<span id="cb39-374"><a href="#cb39-374" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TARGET) <span class="sc">|&gt;</span></span>
<span id="cb39-375"><a href="#cb39-375" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb39-376"><a href="#cb39-376" aria-hidden="true" tabindex="-1"></a>    <span class="at">Applicants =</span> <span class="fu">n</span>(),</span>
<span id="cb39-377"><a href="#cb39-377" aria-hidden="true" tabindex="-1"></a>    <span class="at">Average_Credit =</span> <span class="fu">mean</span>(AMT_CREDIT, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb39-378"><a href="#cb39-378" aria-hidden="true" tabindex="-1"></a>    <span class="at">Median_Credit =</span> <span class="fu">median</span>(AMT_CREDIT, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-379"><a href="#cb39-379" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb39-380"><a href="#cb39-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-381"><a href="#cb39-381" aria-hidden="true" tabindex="-1"></a>credit_summary</span>
<span id="cb39-382"><a href="#cb39-382" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-383"><a href="#cb39-383" aria-hidden="true" tabindex="-1"></a>Applicants with payment difficulty had a somewhat lower median requested credit amount than applicants without payment difficulty. The median credit amount was 497,520 for applicants with payment difficulty compared with 517,788 for those without payment difficulty. Although the difference is not large, it suggests that requested credit amount may contain some information related to payment difficulty. Therefore, credit amount should be retained and evaluated as a potential predictor during modeling.</span>
<span id="cb39-384"><a href="#cb39-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-385"><a href="#cb39-385" aria-hidden="true" tabindex="-1"></a><span class="fu">### What Relationships Exist Among Key Financial Variables Such as Income, Credit Amount, and Annuity Amount?</span></span>
<span id="cb39-386"><a href="#cb39-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-387"><a href="#cb39-387" aria-hidden="true" tabindex="-1"></a>Income, credit amount, and loan annuity are examined together to determine whether these financial variables are strongly related. Strong relationships between predictors may be important to consider during later data preparation and modeling.</span>
<span id="cb39-390"><a href="#cb39-390" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-391"><a href="#cb39-391" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine correlations among key financial variables</span></span>
<span id="cb39-392"><a href="#cb39-392" aria-hidden="true" tabindex="-1"></a>application_train <span class="sc">|&gt;</span></span>
<span id="cb39-393"><a href="#cb39-393" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(AMT_INCOME_TOTAL, AMT_CREDIT, AMT_ANNUITY) <span class="sc">|&gt;</span></span>
<span id="cb39-394"><a href="#cb39-394" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>(<span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb39-395"><a href="#cb39-395" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-396"><a href="#cb39-396" aria-hidden="true" tabindex="-1"></a>The financial variables show different levels of association with one another. AMT_CREDIT and AMT_ANNUITY have a relatively strong positive correlation of approximately 0.77, which is reasonable because larger loans generally require larger annuity payments. In contrast, applicant income has much weaker relationships with credit and annuity amounts. The strong relationship between credit and annuity suggests that these variables may contain overlapping information. Both should still be evaluated during modeling, but their relationship should be considered when assessing their predictive contribution.</span>
<span id="cb39-397"><a href="#cb39-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-398"><a href="#cb39-398" aria-hidden="true" tabindex="-1"></a><span class="fu"># Conclusion</span></span>
<span id="cb39-399"><a href="#cb39-399" aria-hidden="true" tabindex="-1"></a>The exploratory analysis identified several important characteristics and data-quality issues in the Home Credit application data. Payment difficulty occurs in approximately 8.1% of the training applications, creating a substantial class imbalance that should be considered when evaluating predictive models. Several housing and property variables contain more than 65% missing values and should be evaluated individually during data preparation to determine whether they provide enough information to retain or impute. Missingness in COMMONAREA_AVG was also associated with payment difficulty, with an 8.57% payment-difficulty rate when the value was missing compared with 6.91% when it was not missing. This suggests that missingness itself may contain useful predictive information. In addition, DAYS_EMPLOYED contains the special value 365243 for approximately 18.0% of applications and should be treated separately rather than as a valid employment duration.</span>
<span id="cb39-400"><a href="#cb39-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-401"><a href="#cb39-401" aria-hidden="true" tabindex="-1"></a>The EDA also identified several variables that may contain useful information for predicting payment difficulty. Applicants with payment difficulty were younger on average, with an average age of 40.8 years compared with 44.2 years for applicants without payment difficulty. They also had a lower median income of 135,000 compared with 148,500 and a somewhat lower median requested credit amount of 497,520 compared with 517,788. These relationships do not establish causation, but they suggest that age, income, and credit characteristics should be evaluated as potential predictors during modeling. AMT_CREDIT and AMT_ANNUITY were also strongly positively correlated at approximately 0.77, indicating that they may contain overlapping information.</span>
<span id="cb39-402"><a href="#cb39-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-403"><a href="#cb39-403" aria-hidden="true" tabindex="-1"></a>Overall, the EDA supports the business problem identified at the beginning of the project: payment difficulty appears to be associated with multiple aspects of an applicant's financial and personal characteristics rather than a single variable. The analysis did not change the planned predictive-classification approach, but it clarified important data-preparation decisions and identified several variables and relationships that should be evaluated further during feature engineering and modeling.</span>
<span id="cb39-404"><a href="#cb39-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-405"><a href="#cb39-405" aria-hidden="true" tabindex="-1"></a><span class="fu"># AI Use</span></span>
<span id="cb39-406"><a href="#cb39-406" aria-hidden="true" tabindex="-1"></a>ChatGPT was used to assist with developing and debugging R code, organizing the exploratory analysis, and improving the clarity of written interpretations. All code was run in Positron, and the resulting tables and visualizations were reviewed before conclusions were added to the notebook. AI was useful for generating and troubleshooting code, while reviewing the outputs was necessary to determine which findings were meaningful for the Home Credit business problem and what decisions should be carried forward into data preparation and modeling.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>